wordpress:
  container_name: <%= appRoot %>-wp
  image: joonasy/wordpress
  links:
    - database:mysql
  ports:
    - 80:80
  volumes:
    - ../<%= appRoot %>:/var/www/html/wp-content/themes/<%= appRoot %>
    - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
    - ./wp-content/plugins:/var/www/html/wp-content/plugins
    - ./wp-content/uploads:/var/www/html/wp-content/uploads
    - ./wp-config.php:/var/www/html/wp-config.php
    - ./wp-config.dev.php:/var/www/html/wp-config.dev.php
  environment:
    WORDPRESS_DB_NAME: <%= dbName %>
    WORDPRESS_DB_USER: <%= dbUser %>
    USE_EXTERNAL_FILES: 'true'
database:
  container_name: <%= appRoot %>-db
  image: mariadb
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: <%= dbPassword %>
